#!/hint/bash

# C/C++编译参数
CFLAGS="-march=native -mtune=native -O2 -pipe -fno-plt -fexceptions \
        -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security \
        -fstack-clash-protection -fcf-protection \
        -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer"
CXXFLAGS="${CFLAGS} -Wp,-D_GLIBCXX_ASSERTIONS"

# 链接参数
LDFLAGS="-Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now \
         -Wl,-z,pack-relative-relocs"

# Rust编译参数
RUSTFLAGS="-C force-frame-pointers=yes -C target-cpu=native -C opt-level=3"

# 构建环境变量
BUILDENV=(!distcc color !ccache check !sign)

# make命令参数
MAKEFLAGS="-j$(nproc) --quiet"

# 打包选项
OPTIONS=(strip docs !libtool !staticlibs emptydirs zipman purge !debug lto)

# Golang编译变量
export GOAMD64=v3
