#!/hint/bash

# C/C++编译参数
CFLAGS="-march=native -mtune=native -O2 -pipe -fno-plt -fexceptions \
        -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security \
        -fstack-clash-protection -fcf-protection"
CXXFLAGS="${CFLAGS} -Wp,-D_GLIBCXX_ASSERTIONS"

# 链接参数
LDFLAGS="-Wl,-O4,--sort-common,--as-needed,-z,relro,-z,now,-z,defs"

# Rust编译参数
RUSTFLAGS="-C target-cpu=native -C opt-level=3"

# 构建环境变量
BUILDENV=(!distcc color !ccache check !sign)

# make命令参数
MAKEFLAGS="-j$(nproc) --quiet"

OPTIONS=(strip docs !libtool !staticlibs emptydirs zipman purge !debug lto)

# 压缩参数
COMPRESSGZ=(gzip -c -f -n --best)
COMPRESSBZ2=(bzip2 -c -f --best)
COMPRESSXZ=(xz -T 0 -c -z --best -)
COMPRESSZST=(zstd -c -T0 -5 -)
COMPRESSLRZ=(lrzip -9 -q)
COMPRESSLZO=(lzop -q --best)
COMPRESSZ=(compress -c -f)
COMPRESSLZ4=(lz4 -q --best)
COMPRESSLZ=(lzip -c -f)

# Golang编译变量
export GOAMD64=v3
