[sync]
alwaysshowpkgorigin = no
develpkgsexpiration = -1
upgradesorting = versiondiff
showdownloadsize = no
ignoreoutofdateaurupgrades = no

[build]
keepbuilddir = no
keepdevbuilddir = no
keepbuilddeps = yes
gpgdir = 
skipfailedbuild = no
dynamicusers = root
ignorearch = no

[review]
noedit = no
donteditbydefault = no
nodiff = no
gitdiffargs = --ignore-space-change,--ignore-all-space
diffpager = auto
hidedifffiles = .SRCINFO

[colors]
version = 10
versiondiffold = 11
versiondiffnew = 9

[ui]
requireenterconfirm = yes
printcommands = no
aursearchsorting = hottest
displaylastupdated = no
groupbyrepository = yes
reversesearchsorting = yes
warnaboutpackageupdates = 

[misc]
pacmanpath = pacman
privilegeescalationtool = sudo
privilegeescalationtarget = pikaur
userid = 0
preserveenv = PKGDEST,VISUAL,EDITOR,http_proxy,https_proxy,ftp_proxy,HTTP_PROXY,HTTPS_PROXY,FTP_PROXY,ALL_PROXY,RUSTUP_HOME,CARGO_HOME,GOMODCACHE,GOPATH,NPM_CONFIG_USERCONFIG,GNUPGHOME,NUGET_PACKAGES

[network]
aururl = https://aur.archlinux.org
newsurl = https://www.archlinux.org/feeds/news/
socks5proxy = 
aurhttpproxy = 
aurhttpsproxy = 

