[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "target-cpu=native", "-C", "opt-level=3"]

[source.crates-io]
replace-with = 'bfsu'

[source.bfsu]
registry = "sparse+https://mirrors.bfsu.edu.cn/crates.io-index/"
